services:
  - type: web
    name: mohd-adeeb-portfolio
    runtime: static
    buildCommand: npm install; npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 20
